[package]
name = "poplar_blossom"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_common_assets = {version = "0.10.0", features = ["csv"]}
bevy_rapier3d = "0.25.0"
csv = "1.3.0"
meshtext = "0.3.0"
serde = "1.0.201"
thiserror = "1.0.60"
